import datetime
x = datetime.datetime.now()
print(x)
print(x.strftime("%B"))
print(x.year)
print(x.month)
print(x.day)
print(x.date())
print(x.time())
y = datetime.datetime(2023,8,19)
print(y)
print(y.year)
print(y.month)
print(y.day)
print(y.date())
print(y.time())
